import { NavLink, Property, School, Neighborhood, CostOfLiving, FAQ, Currency } from './types';

export const NAV_LINKS: NavLink[] = [
  { id: 'home', label: 'Inicio' },
  { id: 'permits', label: 'Permisos' },
  { id: 'housing', label: 'Vivienda' },
  { id: 'schools', label: 'Colegios' },
  { id: 'neighborhoods', label: 'Barrios' },
  { id: 'taxation', label: 'Impuestos' },
  { id: 'social-security', label: 'Seguridad Social' },
  { id: 'faq', label: 'FAQ' },
  { id: 'contact', label: 'Contacto' },
];

export const PROPERTIES: Property[] = [
  {
    id: '1',
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    price: 1200000,
    type: 'Alquiler',
    propertyType: 'Apartamento',
    title: 'Moderno Apartamento en Villa Morra',
    location: 'Villa Morra',
    city: 'Asunción',
    area: 120,
    bedrooms: 3,
    bathrooms: 2,
  },
  {
    id: '2',
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
    price: 450000000,
    type: 'Venta',
    propertyType: 'Casa',
    title: 'Casa de Lujo en Barrio Carmelitas',
    location: 'Carmelitas',
    city: 'Asunción',
    area: 350,
    bedrooms: 4,
    bathrooms: 3,
  },
  {
    id: '3',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
    price: 950000,
    type: 'Alquiler',
    propertyType: 'Apartamento',
    title: 'Apartamento Frente al Rio',
    location: 'Centro',
    city: 'Asunción',
    area: 95,
    bedrooms: 2,
    bathrooms: 2,
  },
  {
    id: '4',
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
    price: 380000000,
    type: 'Venta',
    propertyType: 'Casa',
    title: 'Residencia en Luque',
    location: 'Centro',
    city: 'Luque',
    area: 280,
    bedrooms: 3,
    bathrooms: 2,
  },
  {
    id: '5',
    image: 'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800',
    price: 280000000,
    type: 'Venta',
    propertyType: 'Casa',
    title: 'Casa Moderna en Ciudad del Este',
    location: 'Zona Urbana',
    city: 'Ciudad del Este',
    area: 200,
    bedrooms: 3,
    bathrooms: 2,
  },
  {
    id: '6',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    price: 1500000,
    type: 'Alquiler',
    propertyType: 'Apartamento',
    title: 'Penthouse de Lujo',
    location: 'Mburucuyá',
    city: 'Asunción',
    area: 180,
    bedrooms: 3,
    bathrooms: 3,
  },
];

export const SCHOOLS: School[] = [
  {
    id: '1',
    name: 'Colegio Técnico Nacional de Asunción (CTN)',
    image: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800',
    location: 'R.I. 3 Corrales c/ Dr. Hassler',
    city: 'Asunción',
    languages: ['Español', 'Guaraní'],
    levels: ['Secundaria'],
    ranking: 4,
    description: 'Institución pública técnica con alta demanda. Ofrece 485 plazas en diversas especialidades técnicas.',
    type: 'Público',
    specialties: ['Informática', 'Electrónica', 'Construcciones Civiles', 'Química Industrial', 'Electromecánica', 'Mecánica Automotriz'],
    costs: 'Gratuito',
    admissionRequirements: 'Promedio brillante, certificado de estudios, examen de admisión',
  },
  {
    id: '2',
    name: 'Colegio Santa Clara',
    image: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=800',
    location: 'Av. Mariscal López 3150',
    city: 'Asunción',
    languages: ['Español', 'Inglés'],
    levels: ['Primaria', 'Secundaria'],
    ranking: 5,
    description: 'Colegio privado de alto prestigio con bachilleratos científicos y técnicos.',
    type: 'Privado',
    specialties: ['Científico', 'Técnico', 'Ciencias Sociales', 'Ciencias Básicas'],
    costs: 'Matrícula: ₲1.700.000–₲2.350.000 · Cuota: ₲1.355.000–₲1.710.000',
    admissionRequirements: 'Promedio mínimo 3 o 4, boletín de calificaciones, prueba de Matemática y Lengua',
  },
  {
    id: '3',
    name: 'American School of Asunción (ASA)',
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800',
    location: 'Avenida España 1175',
    city: 'Asunción',
    languages: ['Inglés', 'Español'],
    levels: ['Preescolar', 'Primaria', 'Secundaria'],
    ranking: 5,
    description: 'Currículo americano con Bachillerato Internacional (IB) y acreditación internacional.',
    type: 'Privado',
    specialties: ['Bachillerato Internacional (IB)', 'Programas EE.UU.', 'Programas Paraguay'],
    costs: 'Admisión: USD 7.000 · Matrícula: USD 700 · Cuota anual: ₲46.292.718',
    admissionRequirements: 'Prioridad diplomáticos/hijos de graduados, test de evaluación (USD 110)',
  },
  {
    id: '4',
    name: 'Trinity School',
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800',
    location: 'Luque',
    city: 'Luque',
    languages: ['Inglés', 'Español'],
    levels: ['Preescolar', 'Primaria', 'Secundaria'],
    ranking: 5,
    description: 'Educación bilingüe con enfoque STEAM y formación integral.',
    type: 'Privado',
    specialties: ['Educación Bilingüe', 'STEAM'],
    costs: 'Admisión: USD 3.500 · Matrícula: USD 700 · Cuota: ₲3.200.000',
    admissionRequirements: 'Entrevistas, evaluaciones, exámenes de Matemáticas e Inglés, evaluación psicológica',
  },
  {
    id: '5',
    name: 'Colegio Internacional (Inter)',
    image: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800',
    location: 'Río de Janeiro c/ Padre Saubatte',
    city: 'Asunción',
    languages: ['Español', 'Inglés', 'Guaraní'],
    levels: ['Preescolar', 'Primaria', 'Secundaria'],
    ranking: 5,
    description: 'Bachilleratos con énfasis deportivo/cultural y técnico en administración.',
    type: 'Privado',
    specialties: ['Deportivo/Cultural', 'Administración de Negocios', 'Científico', 'Letras y Artes'],
    costs: 'Admisión: USD 2.000 · Cuota: ₲3.100.000',
    admissionRequirements: 'Entrevistas, evaluaciones y exámenes de admisión',
  },
  {
    id: '6',
    name: 'SEK Paraguay International School',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800',
    location: 'C/ Mercedes Grau',
    city: 'Lambaré',
    languages: ['Español', 'Inglés', 'Guaraní'],
    levels: ['Preescolar', 'Primaria', 'Secundaria'],
    ranking: 5,
    description: 'Bachillerato Internacional (IB) con educación trilingüe.',
    type: 'Privado',
    specialties: ['Bachillerato Internacional (IB)', 'Trilingüe'],
    costs: 'Admisión: USD 1.000 · Matrícula: ₲1.700.000 · Cuota: ₲2.288.000',
    admissionRequirements: 'Examen de evaluación (₲255.000), entrevista psicopedagógica',
  },
  {
    id: '7',
    name: 'Liberty School of Education',
    image: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=800',
    location: 'Cerca de Av. Mariscal López',
    city: 'Fernando de la Mora',
    languages: ['Español', 'Inglés'],
    levels: ['Preescolar', 'Primaria', 'Secundaria'],
    ranking: 4,
    description: 'Educación bilingüe con formación integral desde nivel inicial.',
    type: 'Privado',
    specialties: ['Nivel Inicial', 'Nivel Medio'],
    costs: 'Admisión: USD 1.000 · Matrícula: USD 572 · Cuota: ₲2.256.750–₲2.500.000',
    admissionRequirements: 'Entrevistas, evaluaciones y abono de cuota de admisión',
  },
  {
    id: '8',
    name: "St. Anne's School (SAS)",
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800',
    location: 'Tte. Manuel Pino González y Eulalio Facetti',
    city: 'Asunción',
    languages: ['Inglés', 'Español'],
    levels: ['Primaria', 'Secundaria'],
    ranking: 5,
    description: 'Currículo británico con certificaciones IGCSE y A-Levels.',
    type: 'Privado',
    specialties: ['Curriculum Británico', 'IGCSE', 'A-Levels'],
    costs: 'Admisión: USD 3.200 · Matrícula: USD 840 · Cuota: ₲2.940.000',
    admissionRequirements: 'Entrevistas y evaluaciones de admisión',
  },
  {
    id: '9',
    name: 'Colegio del Sol',
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800',
    location: 'Asunción',
    city: 'Asunción',
    languages: ['Español', 'Inglés'],
    levels: ['Primaria', 'Secundaria'],
    ranking: 4,
    description: 'Bachillerato científico y educación media de calidad.',
    type: 'Privado',
    specialties: ['Bachillerato Científico', 'Media'],
    costs: 'Admisión: USD 400 · Matrícula: ₲2.200.000 · Cuota: ₲2.380.000',
    admissionRequirements: 'Test de evaluación (₲200.000), libreta de calificaciones',
  },
  {
    id: '10',
    name: 'Pan American International School',
    image: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800',
    location: 'Luque',
    city: 'Luque',
    languages: ['Inglés', 'Español'],
    levels: ['Preescolar', 'Primaria', 'Secundaria'],
    ranking: 5,
    description: 'Educación internacional de alto nivel con formación bilingüe.',
    type: 'Privado',
    specialties: ['Educación Internacional'],
    costs: 'Admisión: ₲29.320.000 · Matrícula: ₲5.864.000 · Cuota: ₲3.400.000',
    admissionRequirements: 'Entrevistas, evaluaciones y exámenes de admisión',
  },
  {
    id: '11',
    name: 'Colegio Lumen',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800',
    location: 'Asunción',
    city: 'Asunción',
    languages: ['Español', 'Inglés'],
    levels: ['Preescolar', 'Primaria', 'Secundaria'],
    ranking: 4,
    description: 'Formación integral con enfoque en valores y excelencia académica.',
    type: 'Privado',
    specialties: ['Formación Integral'],
    costs: 'Matrícula: ₲7.330.000 · Cuota: ₲3.000.000',
    admissionRequirements: 'Entrevistas, evaluaciones y exámenes de admisión',
  },
  {
    id: '12',
    name: 'Aula Viva',
    image: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=800',
    location: 'Asunción',
    city: 'Asunción',
    languages: ['Español', 'Inglés'],
    levels: ['Preescolar', 'Primaria', 'Secundaria'],
    ranking: 4,
    description: 'Educación innovadora con enfoque en aprendizaje activo.',
    type: 'Privado',
    specialties: ['Aprendizaje Activo'],
    costs: 'Admisión familiar: ₲10.995.000 · Matrícula: ₲3.000.000 · Cuota: ₲2.500.000',
    admissionRequirements: 'Entrevistas, evaluaciones y exámenes de admisión',
  },
  {
    id: '13',
    name: 'Colegio de la Asunción',
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800',
    location: 'Fernando de la Mora',
    city: 'Fernando de la Mora',
    languages: ['Español', 'Inglés'],
    levels: ['Preescolar', 'Primaria', 'Secundaria'],
    ranking: 4,
    description: 'Institución con tradición educativa y formación integral.',
    type: 'Privado',
    specialties: ['Formación Integral'],
    costs: 'Admisión: ₲4.398.000 · Matrícula: ₲1.800.000 · Cuota: ₲2.570.000',
    admissionRequirements: 'Entrevistas, evaluaciones y exámenes de admisión',
  },
  {
    id: '14',
    name: 'Colegio de San José',
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800',
    location: 'España y San José',
    city: 'Asunción',
    languages: ['Español', 'Guaraní'],
    levels: ['Primaria', 'Secundaria'],
    ranking: 4,
    description: 'Institución tradicional con bachilleratos técnicos y científicos.',
    type: 'Privado',
    specialties: ['Ciencias Básicas', 'Ciencias Sociales', 'Diseño Gráfico', 'Administración de Negocios'],
    costs: 'Consultar con la institución',
    admissionRequirements: 'Formulario de postulación, entrevista, documentos de identidad y bautismo',
  },
  {
    id: '15',
    name: 'Colegio Goethe',
    image: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800',
    location: 'San Lorenzo',
    city: 'San Lorenzo',
    languages: ['Alemán', 'Español', 'Inglés'],
    levels: ['Preescolar', 'Primaria', 'Secundaria'],
    ranking: 5,
    description: 'Educación alemana con triple titulación y reconocimiento internacional.',
    type: 'Privado',
    specialties: ['Triple Titulación', 'Educación Alemana'],
    costs: 'Consultar con la institución',
    admissionRequirements: 'Entrevistas, evaluaciones y exámenes de admisión',
  },
  {
    id: '16',
    name: 'Colegio Experimental Paraguay Brasil (CEPB-UNA)',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800',
    location: 'Campus de la UNA',
    city: 'San Lorenzo',
    languages: ['Español', 'Portugués'],
    levels: ['Secundaria'],
    ranking: 5,
    description: 'Formación integral y bilingüe, entre los más prestigiosos del país.',
    type: 'Público',
    specialties: ['Formación Integral', 'Bilingüismo'],
    costs: 'Gratuito',
    admissionRequirements: 'Examen de admisión competitivo',
  },
];

export const NEIGHBORHOODS: Neighborhood[] = [
  {
    id: '1',
    name: 'Villa Morra',
    city: 'Asunción',
    image: 'https://images.unsplash.com/photo-1480074568708-e7b720bb3f09?w=800',
    description: 'El barrio más dinámico de Asunción. Combina oferta gastronómica de primer nivel con infraestructura de servicios que permite vivir sin grandes desplazamientos. La vida social y el trabajo remoto convergen aquí.',
    tags: ['Moderno', 'Gastronómico', 'Vida Nocturna', 'Coworking'],
    profile: 'Nómadas Digitales y Parejas Trabajadoras',
    highlights: ['Cafés con Wi-Fi de alta velocidad', 'Edificios con amenities (piscinas, gimnasios, coworking)', 'Shopping Mariscal y Paseo Carmelitas', 'Espacios como Loffice Bulnes y El Café de Acá'],
  },
  {
    id: '2',
    name: 'Las Mercedes',
    city: 'Asunción',
    image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
    description: 'Conocido como el "SoHo" asunceno, preserva su arquitectura clásica mientras integra una escena cultural y gastronómica artesanal. Refugio de artistas, diseñadores y dueños de startups.',
    tags: ['Bohemio', 'Creativo', 'Artesanal', 'Cultural'],
    profile: 'Emprendedores y Nómadas Digitales',
    highlights: ['Calles arboladas y galerías de arte', 'Street food y restaurantes de autor', 'Colors Coworking para pequeñas empresas', 'Networking orgánico y atmósfera creativa'],
  },
  {
    id: '3',
    name: 'Ykua Saty',
    city: 'Asunción',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800',
    description: 'El crecimiento vertical más agresivo de la capital. Aquí se encuentran las torres de oficinas más importantes, incluyendo el World Trade Center, Paseo La Galería y Shopping del Sol.',
    tags: ['Corporativo', 'Lujo', 'Comercial', 'Vertical'],
    profile: 'Empleados de Multinacionales y Ejecutivos',
    highlights: ['Edificios corporativos clase A', 'Departamentos de lujo con seguridad 24/7', 'World Trade Center y Paseo La Galería', 'Cercanía a sanatorios de alta complejidad'],
  },
  {
    id: '4',
    name: 'Las Lomas (Carmelitas)',
    city: 'Asunción',
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
    description: 'Históricamente uno de los barrios más prestigiosos, ofrece residencias de lujo y proximidad a los mejores centros educativos de la ciudad.',
    tags: ['Exclusivo', 'Familias', 'Seguro', 'Educación'],
    profile: 'Familias con Hijos Pequeños y Expatriados',
    highlights: ['Colegios de élite: Santa Clara, SIL', 'Mayor patrullaje privado y presencia policial', 'Calles amplias y arboladas', 'Abundantes espacios verdes para paseos familiares'],
  },
  {
    id: '5',
    name: 'Los Laureles',
    city: 'Asunción',
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
    description: 'Barrio eminentemente residencial, con una escala mucho más humana y tranquila que los barrios comerciales adyacentes. Ideal para la vida familiar.',
    tags: ['Residencial', 'Tranquilo', 'Parques', 'Familiar'],
    profile: 'Familias con Hijos Pequeños',
    highlights: ['Plazas y parques bien mantenidos', 'Supermercados de cadena y servicios de proximidad', 'Casas amplias con jardín', 'Edificios de mediana altura con enfoque familiar'],
  },
  {
    id: '6',
    name: 'San Cristóbal',
    city: 'Asunción',
    image: 'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800',
    description: 'Estratégicamente ubicado entre el eje corporativo y las zonas residenciales tradicionales. El barrio de la logística y el movimiento comercial.',
    tags: ['Estratégico', 'Comercial', 'Conectado', 'Accesible'],
    profile: 'Comerciales y Vendedores Independientes',
    highlights: ['Acceso directo a Av. Mariscal López y Aviadores del Chaco', 'Punto medio para visitar clientes y proveedores', 'Oficinas comerciales accesibles', 'Excelente relación calidad-precio'],
  },
  {
    id: '7',
    name: 'Recoleta / San Blas',
    city: 'Asunción',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    description: 'En el centro geográfico de las zonas de mayor interés. Ofrece una alternativa más serena a Villa Morra, pero con beneficios similares.',
    tags: ['Equilibrado', 'Gastronómico', 'Céntrico', 'Moderno'],
    profile: 'Parejas Trabajadoras y Jóvenes Profesionales',
    highlights: ['Minutos de cualquier punto del eje comercial', 'Oferta gastronómica propia en crecimiento', 'Cercanía al Sanatorio Adventista', 'Alquileres modernos y funcionales'],
  },
  {
    id: '8',
    name: 'Mburucuyá',
    city: 'Asunción',
    image: 'https://images.unsplash.com/photo-1600566753086-00f18d6885e5?w=800',
    description: 'Uno de los barrios más verdes de Asunción, con baja densidad poblacional y atmósfera de tranquilidad absoluta. El "barrio jardín" de la capital.',
    tags: ['Verde', 'Tranquilo', 'Seguro', 'Residencial'],
    profile: 'Familias y Amantes de la Naturaleza',
    highlights: ['Abundante vegetación y calles empedradas', 'Temperatura más fresca en verano', 'Bajo índice de incidentes', 'Comunidad segura y tranquila'],
  },
  {
    id: '9',
    name: 'Barrio Jara',
    city: 'Asunción',
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800',
    description: 'Cerca de importantes universidades, ha rejuvenecido gracias a inversión en departamentos para jóvenes y locales de ocio alternativo.',
    tags: ['Universitario', 'Joven', 'Asequible', 'Cultural'],
    profile: 'Emprendedores Jóvenes y Estudiantes',
    highlights: ['Ambiente joven y dinámico', 'Bares y cafeterías más asequibles', 'Bajos costos para oficinas pequeñas', 'Proximidad a centros culturales y bibliotecas'],
  },
  {
    id: '10',
    name: 'Manorá',
    city: 'Asunción',
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
    description: 'Pequeño pero exclusivo, sirve de puente entre la sofisticación de Villa Morra y el poder corporativo de Ykua Saty.',
    tags: ['Lujo', 'Exclusivo', 'Premium', 'Moderno'],
    profile: 'Ejecutivos de Multinacionales y Parejas de Alto Poder Adquisitivo',
    highlights: ['Edificios más lujosos y modernos de la ciudad', 'A 5 min de principales centros de negocios', 'Tranquilidad residencial de élite', 'Estética arquitectónica de vanguardia'],
  },
];

export const COST_OF_LIVING: CostOfLiving[] = [
  {
    city: 'Asunción',
    rent1br: 2500000,
    rent3br: 4500000,
    utilities: 450000,
    food: 2000000,
    transport: 300000,
    entertainment: 800000,
    total: 10550000,
  },
  {
    city: 'Ciudad del Este',
    rent1br: 1800000,
    rent3br: 3200000,
    utilities: 350000,
    food: 1600000,
    transport: 250000,
    entertainment: 600000,
    total: 7800000,
  },
  {
    city: 'Encarnación',
    rent1br: 1500000,
    rent3br: 2800000,
    utilities: 300000,
    food: 1400000,
    transport: 200000,
    entertainment: 500000,
    total: 6700000,
  },
];

export const FAQS: FAQ[] = [
  {
    question: '¿Cuánto tiempo toma obtener la residencia temporal?',
    answer: 'El proceso de residencia temporal generalmente toma entre 2 a 4 meses, dependiendo de la correcta preparación de documentos y la carga de trabajo de las instituciones. Una vez aprobada, la residencia se otorga por 2 años.',
  },
  {
    question: '¿Necesito apostillar todos mis documentos?',
    answer: 'Sí, todos los documentos emitidos en el extranjero deben llevar la Apostilla de La Haya. Esto incluye certificados de nacimiento, antecedentes penales, certificados de matrimonio, títulos profesionales, entre otros.',
  },
  {
    question: '¿Cuánto dinero debo depositar para la residencia?',
    answer: 'Para la residencia temporal vía general, se requiere demostrar solvencia económica, típicamente mediante un depósito bancario de aproximadamente $5,000 USD. Para la vía inversionista SUACE, los requisitos de inversión son mayores y específicos al tipo de empresa.',
  },
  {
    question: '¿Puedo trabajar con residencia temporal?',
    answer: 'Sí, la residencia temporal te permite trabajar en Paraguay. Sin embargo, necesitarás obtener la Cédula de Identidad Paraguaya para poder firmar contratos laborales formales y abrir cuentas bancarias.',
  },
  {
    question: '¿Qué impuestos debo pagar como residente?',
    answer: 'Paraguay aplica el sistema de renta territorial, lo que significa que solo pagas impuestos por ingresos generados dentro del país. Los principales impuestos son el IRP (Impuesto a la Renta Personal) para empleados y el IVA para independientes. Las tasas son muy competitivas en comparación con otros países de la región.',
  },
  {
    question: '¿Es obligatorio el seguro de salud IPS?',
    answer: 'El IPS es obligatorio para trabajadores en relación de dependencia. Los aportes son compartidos: el empleado aporta el 9% y el empleador el 16.5% del salario. Los trabajadores independientes pueden optar voluntariamente por afiliarse.',
  },
  {
    question: '¿Puedo obtener la ciudadanía paraguaya?',
    answer: 'Sí, después de 3 años de residencia permanente ininterrumpida, puedes solicitar la ciudadanía paraguaya por naturalización. Esto requiere demostrar conocimientos básicos de español o guaraní y aprobación de un examen.',
  },
  {
    question: '¿Necesito un traductor público para mis documentos?',
    answer: 'Sí, todos los documentos en idioma extranjero deben ser traducidos por un Traductor Público matriculado en Paraguay. La traducción debe ser legalizada ante escribano público.',
  },
];

export const CURRENCIES: Currency[] = [
  { code: 'PYG', symbol: '₲', rate: 1 },
  { code: 'USD', symbol: '$', rate: 7300 },
  { code: 'EUR', symbol: '€', rate: 8000 },
];

export const SOCIAL_LINKS = {
  facebook: 'https://facebook.com',
  instagram: 'https://instagram.com',
  youtube: 'https://youtube.com',
};

export const CONTACT_INFO = {
  email: 'info@livingparaguay.com',
  phone: '+595 21 123 4567',
  whatsapp: '+595981123456',
};
